# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: DockerCompose@1
  inputs:
    containerregistrytype: "Azure Container Registry"
    dockerComposeFile: src/docker-compose.yml
    additionalDockerComposeFiles: ../ci/docker-compose.ci.yml
    projectName: "northwindstore"
    action: "Run a Docker Compose command"
    dockerComposeCommand: "up"
    arguments: --build --force-recreate -d
- task: Docker@1
  inputs:
    command: "build"
    containerName: "northwindstoretestsunittests"
    dockerFile: src/NorthwindStore.Tests.UnitTests/Dockerfile
    buildContext: "src"
    imageName: $(Build.BuildId)
- task: Docker@2
  inputs:
    command: "run"
    arguments: --rm northwindstoretestsunittests:$(Build.BuildId)
- task: Docker@2
  inputs:
    arguments: --rm -e "ConnectionStrings__DB=Data Source=tcp:northwindstore.db,1433; Initial Catalog=Northwind; User ID=sa; Password=DevPass_1" --network northwindstore-dev northwindstoretestsintegrationtests:$(Build.BuildId)
    containerName: "northwindstoretestsintegrationtests"
    dockerFile: src/NorthwindStore.Tests.IntegrationTests/Dockerfile



